version: "3.9"

services:

  backend:
    build: ./backend
    container_name: backend-container
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    container_name: frontend-container
    ports:
      - "8080:80"